apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabiga-demo-api
  namespace: NAMESPACE
  labels:
    app: rabiga-demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabiga-demo-api
  template:
    metadata:
      labels:
        app: rabiga-demo-api
    spec:
      containers:
      - name: rabiga-demo-api
        image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/apiapp:IMAGEVERSION
        ports:
        - containerPort: 80
